namespace :git do
  desc 'symlink git dotfiles' 
  task :symlink do
    within File.expand_path('../', __FILE__) do
      dotfiles = Dir['.*'] - %w(. ..)
      dotfiles.each do |filename|
        symlink File.expand_path(filename), home_path
      end
    end
  end
end

after 'update', 'git:symlink'
