namespace :vim do
  desc 'symlink vim dotfiles'
  task :symlink do
    within File.expand_path('../', __FILE__) do
      dotfiles = Dir['.*'] - %w(. ..)
      dotfiles.each do |filename|
        symlink File.expand_path(filename), home_path
      end
    end
  end

  desc 'update vim bundles'
  task :update do
    sh 'vim', '-e', '+NeoBundleUpdate', '+qall'
  end
end

after 'symlink', 'vim:symlink'
after 'update', 'vim:update'
