namespace :vim do
  namespace :submodule do
    desc 'add vim submodules'
    task :add do
      sh 'git', 'submodule', 'add', 'git@github.com:Shougo/neobundle.vim.git', 'vim/.vim/bundle/neobundle.vim' rescue nil
    end
  end

  desc 'symlink vim files' 
  task :symlink do
    within File.expand_path('../', __FILE__) do
      %w(.vim .vimrc .gvimrc).each do |filename|
        symlink File.expand_path(filename), home_path
      end
    end
  end

  desc 'update vim bundles' 
  task :update do
    sh 'vim', '-e', '+NeoBundleUpdate', '+qall'
  end
end

before 'git:submodule:update', 'vim:submodule:add'
after 'update', 'vim:symlink'
after 'update', 'vim:update'

