if has? :brew
  namespace :homebrew do
    desc 'install homebrew formula'
    task :install do
      within File.expand_path('../', __FILE__) do
        sh 'install.sh'
      end
    end
  end

  after 'update', 'homebrew:install'
end

