namespace :fish do
  desc 'symlink fish configs'
  task :symlink do
    fish_config_dir = config_path.join('fish')
    FileUtils.mkdir_p fish_config_dir

    ['config.fish', 'fish_plugins'].each do |filename|
      symlink File.expand_path("../#{filename}", __FILE__), fish_config_dir
    end
  end
end

after 'symlink', 'fish:symlink'
